### ISSUE TITLE
Support for Python v3.12

### ISSUE THREAD

**Issue by aiman** [autonity/autonity.py#42]
Currently, importing `autonity.py` on Python 3.12 fails due to `ModuleNotFoundError` triggered by Web3.py:

```
Traceback (most recent call last):
  File "/home/test/test.py", line 1, in <module>
    import autonity
  File "/home/test/.local/share/virtualenvs/test-hFzLK45U/lib/python3.12/site-packages/autonity/__init__.py", line 10, in <module>
    from autonity.autonity import (
  File "/home/test/.local/share/virtualenvs/test-hFzLK45U/lib/python3.12/site-packages/autonity/autonity.py", line 14, in <module>
    from web3 import Web3
  File "/home/test/.local/share/virtualenvs/test-hFzLK45U/lib/python3.12/site-packages/web3/__init__.py", line 2, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by aiman** [comment]
This may fix the issue, but I'm not sure it's the right solution as this project doesn't have a direct dependency on `setuptools`. Rather, it's an upstream problem with Web3.py. Having said that, I have just seen that upstream finally addressed the issue in a new release <https://github.com/ethereum/web3.py/issues/3186>.
